# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Develop CI - Combine filters

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out code from repo
      uses: actions/checkout@v2
  
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Run filter combiner to combine all files
      run: |
        ls
        python ./workers/FilterCombiner.py
    
    - name: Download output file (CustomFiltersSA.txt)
      uses: actions/upload-artifact@v2
      with:
        name: download combined filters text file
        path: |
          CustomFiltersSA.txt
